# 관리자 권한 갖기
sudo: required

# 언어(플랫폼) 선택
language: generic

# 도커 환경 구성
services:
    - docker

# 스크립트를 실행할 수 있는 환경 구성
before_install:
    - echo "start Creating an image with dockerfile"
    - docker build -t jongwoo29/sc-app -f Dockerfile.dev ./

# 실행할 스크립트(테스트실행)
script:
    - docker run -e CI=true jongwoo29/sc-app npm run test -- --coverage

# 테스트 성공 후 할 일
after_success:
    - echo "Test Success"

deploy:
    provider: elasticbeanstalk
    region: "ap-northeast-2"
    app: "sc-app"
    env: "ScApp-env"
    bucket_name: "elasticbeanstalk-ap-northeast-2-637636195396"
    bucket_path: "sc-app"
    on:
        branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_ACCESS_KEY