version: "3"
services:
  react:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
     - "3000:3000"
    # environment:
      # TZ: Asia/Seoul
    volumes:
     - /usr/src/app/node_modules
     - ./:/usr/src/app
     - "/etc/localtime:/etc/localtime:ro" # 컨테이너 타임존을 로컬환경과 동기화
    stdin_open: true
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # environment: 
      # TZ: Asia/Seoul
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
      - "/etc/localtime:/etc/localtime:ro" 
    command: ["npm", "run", "test"]
   